# Generated by Django 3.1.1 on 2020-11-19 13:40

import core_utility
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesAtPlacesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, verbose_name='Activities Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core_utility.places_images, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='AreasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name')),
                ('description', models.TextField(blank=True, max_length=5555, null=True, verbose_name='About Area')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core_utility.places_images, verbose_name='Logo Image')),
                ('location', django.contrib.gis.db.models.fields.PointField(default='POINT(0,0)', srid=4326, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core_utility.places_images, verbose_name='Country Pic')),
                ('description', models.TextField(blank=True, max_length=5555, null=True, verbose_name='About Countary')),
                ('location', django.contrib.gis.db.models.fields.PointField(default='POINT(0,0)', srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=55, unique=True, verbose_name='Category Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core_utility.places_images, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='TravelersUserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(default='POINT(0,0)', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelersVisitingPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('about', models.TextField(max_length=5555, verbose_name='Ábout')),
                ('image', models.ImageField(upload_to=core_utility.places_images, verbose_name='Logo Image')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT(0,0)', null=True, srid=4326, verbose_name='Visiting Place Location')),
                ('activites', models.ManyToManyField(related_name='place_activity', to='travelersPlaces.ActivitiesAtPlacesModel')),
                ('category', models.ManyToManyField(related_name='place_category', to='travelersPlaces.PlaceCategory')),
                ('local_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_area_place', to='travelersPlaces.areasmodel')),
            ],
        ),
    ]
