# Generated by Django 3.1.1 on 2020-10-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelersPlaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerslocation',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
    ]
