# Generated by Django 3.1.1 on 2020-10-08 18:12

import core_utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelersPlaces', '0002_auto_20201008_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelersPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('about', models.TextField(max_length=5555, verbose_name='Ábout')),
                ('main_image', models.ImageField(upload_to=core_utility.places_images)),
                ('place_type', models.CharField(choices=[('historical', 'Historical'), ('religious', 'Religous'), ('theme park', 'Theme Park'), ('zoo park', 'Zoo Park'), ('adventure park', 'Adventure Park'), ('adventure sports', 'Adventure sports'), ('trekking', 'Trekking')], default='historical', max_length=255, verbose_name='Type of Place')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_locations', to='travelersPlaces.travelerslocation')),
            ],
        ),
    ]
