# Generated by Django 3.1.1 on 2020-10-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelersPlaces', '0003_travelersplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerslocation',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
