# Generated by Django 3.1.1 on 2020-12-13 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelersPlaces', '0005_auto_20201213_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelersVisitingPlaceReviewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField(blank=True, max_length=1111, null=True, verbose_name='Reviews')),
                ('rating', models.FloatField(default=1.0, max_length=5.0, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reviews', to='travelersPlaces.travelersvisitingplaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
