# Generated by Django 3.1.1 on 2020-09-22 01:59

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200922_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgencyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='agency_user_profile', to='travelersUsers.users')),
                ('mobile_number', phone_field.models.PhoneField(help_text='Contact Phone Number', max_length=31)),
                ('website', models.CharField(max_length=100, null=True, verbose_name='Website')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('bio', models.TextField(max_length=1000, null=True, verbose_name='BIO')),
                ('pan', models.CharField(blank=True, max_length=40, null=True, verbose_name='PAN')),
                ('profile_pic', models.ImageField(default='', upload_to='agency/profile/')),
                ('agreement', models.ImageField(default='', upload_to='guide/agreement/', verbose_name='Agreement')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Guide Standard Rating')),
                ('number_of_employee', models.IntegerField(verbose_name='Number of employee')),
                ('status', models.BooleanField(default=True, verbose_name='Availability')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_in_top_ten', models.BooleanField(default=False, verbose_name='Top Ten')),
            ],
        ),
    ]
