# Generated by Django 3.1.1 on 2020-09-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelersUsers', '0003_touristuserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TouristUserProfile',
        ),
    ]
