# Generated by Django 3.1.1 on 2020-09-28 06:11

import core_utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelersMedia', '0001_initial'),
        ('travelersUsers', '0002_auto_20200925_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tourist_user_profile', serialize=False, to='travelersUsers.users')),
                ('mobile_number', models.CharField(help_text='Contact Phone Number', max_length=15, verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], default='Male', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=30, verbose_name='Nationality')),
                ('profile_pic', models.ImageField(upload_to=core_utility.profile_image_directory_path)),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to=core_utility.passport_image_directory_path)),
                ('visa_image', models.ImageField(blank=True, null=True, upload_to=core_utility.visa_image_directory_path)),
                ('photos', models.ManyToManyField(blank=True, related_name='tourist_users_photo', to='travelersMedia.ImageModel')),
            ],
        ),
    ]
