# Generated by Django 3.1.1 on 2020-09-30 10:07

import core_utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelersProfiles', '0002_auto_20200930_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristuserprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core_utility.profile_image_directory_path, verbose_name='Profile Pic'),
        ),
    ]
