# Generated by Django 3.1.1 on 2020-09-30 18:30

import core_utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelersProfiles', '0004_guideuserprofile_travelagencyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideuserprofile',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to=core_utility.passport_image_directory_path, verbose_name='Passport Image'),
        ),
    ]
