# Generated by Django 3.1.1 on 2020-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelersProfiles', '0005_auto_20200930_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideuserprofile',
            name='have_vehicle',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=30, verbose_name='Do you have vehicle'),
        ),
    ]
