# Generated by Django 3.1.1 on 2020-10-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelersMedia', '0003_remove_imagemodel_user'),
        ('travelersProfiles', '0006_auto_20200930_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristuserprofile',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='tourist_users_photo', to='travelersMedia.ImageModel'),
        ),
    ]
