# Generated by Django 3.1.1 on 2020-09-30 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelersMedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='users_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
