# Generated by Django 3.1.1 on 2020-11-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelersPlaces', '0001_initial'),
        ('travelersMedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimagemodel',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='travelersPlaces.travelersvisitingplaces'),
        ),
    ]
