# Generated by Django 3.1.1 on 2020-11-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelersMedia', '0002_placeimagemodel_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimagemodel',
            name='uploader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
