# Generated by Django 3.1.1 on 2020-10-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelersMedia', '0002_imagemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='user',
        ),
    ]
